# 第一行加上 MitM 主机名
hostname = api.sofascore.com

# 下面这一整段代码必须在“同一行”里，千万不要按回车换行！
^https?:\/\/api\.sofascore\.com\/.* url script-response-body 
https://raw.githubusercontent.com/CoffeeBrewer86/SofascoreAdblock/refs/heads/main/SofascoreAdblock.js
